resources:
- repo: self

trigger:
- master

jobs:
- job: centos
  displayname: 'CentOS'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: docker@0
    displayname: Build
    inputs:
      action: 'Run an image'
      imageName: ethomson/libgit2-centos:latest
      volumes: |
       $(Build.SourcesDirectory):/src
       $(Build.BinariesDirectory):/build
      envVars: |
       Build.SourcesDirectory=/src
       Build.BinariesDirectory=/build
      workDir: '/build'
      containerCommand: '/src/ci/build.sh'
      detached: false
  - task: docker@0
    displayname: Test
    inputs:
      action: 'Run an image'
      imageName: ethomson/libgit2-centos:latest
      volumes: |
       $(Build.SourcesDirectory):/src
       $(Build.BinariesDirectory):/build
      envVars: |
       Build.SourcesDirectory=/src
       Build.BinariesDirectory=/build
      workDir: '/build'
      containerCommand: '/src/ci/test.sh'
      detached: false
  - task: publishtestresults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'results_*.xml'
      searchFolder: '$(Build.BinariesDirectory)'
      mergeTestResults: true
