resources:
- repo: self

trigger:
- master
- maint/*

jobs:
- job: docs
  displayName: 'Generate Documentation'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: docker@0
    displayName: 'Generate Documentation'
    inputs:
      action: 'Run an image'
      imageName: libgit2/docurium:test
      volumes: |
       $(Build.SourcesDirectory):/src
       $(Build.BinariesDirectory):/build
      envVars: |
       Build.SourcesDirectory=/src
       Build.BinariesDirectory=/build
      workDir: '/src'
      containerCommand: 'cm doc api.docurium'
      detached: false
