resources:
- repo: self

trigger:
- master
- maint/*

jobs:
- job: docs
  displayName: 'Generate Documentation'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      git config user.name 'Documentation Generation'
      git config user.email 'libgit2@libgit2.org'
    displayName: 'Configure Git'
  - task: docker@0
    displayName: 'Generate Documentation'
    inputs:
      action: 'Run an image'
      imageName: libgit2/docurium:test
      volumes: |
       $(Build.SourcesDirectory):/src
      workDir: '/src'
      containerCommand: 'cm doc api.docurium'
      detached: false
  - script: git checkout gh-pages
    displayName: 'Switch to Documentation Branch'
  - task: archivefiles@2
    displayName: 'Archive Documentation'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/api-documentation.zip'
  - task: publishbuildartifacts@1
    displayName: 'Upload Documentation'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'docs'
