/*
 * Copyright (c), Edward Thomson <ethomson@edwardthomson.com>
 * All rights reserved.
 *
 * This file is part of adopt, distributed under the MIT license.
 * For full terms and conditions, see the included LICENSE file.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT.
 *
 * This file was produced by using the `rename.pl` script included with
 * adopt.  The command-line specified was:
 *
 * ./rename.pl gitcli_opt --filename=opt --include=cli.h --inline=GIT_INLINE --header-guard=CLI_opt_h__ --without-usage --lowercase-status
 */

#ifndef CLI_opt_h__
#define CLI_opt_h__

#include <stdio.h>
#include <stdint.h>

/**
 * The type of argument to be parsed.
 */
typedef enum {
	GITCLI_OPT_NONE = 0,

	/**
	 * An argument that, when specified, sets a given value to true.
	 * This is useful for arguments like "--debug".  The `value` pointer
	 * in the returned option will be set to `1` when this is set.
	 */
	GITCLI_OPT_BOOL,

	/**
	 * An argument that, when specified, sets the given `value_ptr`
	 * to the given `value`.
	 */
	GITCLI_OPT_SWITCH,

	/** An argument that has a value ("-nvalue" or "--name value") */
	GITCLI_OPT_VALUE,

	/** An argument that has an optional value ("-n" or "-n foo") */
	GITCLI_OPT_VALUE_OPTIONAL,

	/** The literal arguments follow specifier, bare "--" */
	GITCLI_OPT_LITERAL,

	/** A single "free" argument ("path") */
	GITCLI_OPT_ARG,

	/** Unmatched arguments, a collection of "free" arguments ("paths...") */
	GITCLI_OPT_ARGS,
} gitcli_opt_type_t;

/**
 * Usage information for an argument, to be displayed to the end-user.
 * This is only for display, the parser ignores this usage information.
 */
typedef enum {
	/** This argument is required. */
	GITCLI_OPT_USAGE_REQUIRED = (1u << 0),

	/** This argument should not be displayed in usage. */
	GITCLI_OPT_USAGE_HIDDEN = (1u << 1),

	/** This is a multiple choice argument, combined with the previous arg. */
	GITCLI_OPT_USAGE_CHOICE = (1u << 2),

	/** In usage, show the long format instead of the abbreviated format. */
	GITCLI_OPT_USAGE_SHOW_LONG = (1u << 3),
} gitcli_opt_usage_t;

/** Specification for an available option. */
typedef struct gitcli_opt_spec {
	/** Type of option expected. */
	gitcli_opt_type_t type;

	/** Name of the long option. */
	const char *name;

	/** The alias is the short (one-character) option alias. */
	const char alias;

	/**
	 * If this spec is of type `GITCLI_OPT_BOOL`, this is a pointer to
	 * an `int` that will be set to `1` if the option is specified.
	 *
	 * If this spec is of type `GITCLI_OPT_SWITCH`, this is a pointer to
	 * an `int` that will be set to the opt's `value` (below) when
	 * this option is specified.
	 *
	 * If this spec is of type `GITCLI_OPT_VALUE` or `GITCLI_OPT_VALUE_OPTIONAL`,
	 * this is a pointer to a `char *`, that will be set to the value
	 * specified on the command line.
	 */
	void *value;

	/**
	 * If this spec is of type `GITCLI_OPT_SWITCH`, this is the value to
	 * set in the option's `value_ptr` pointer when it is specified.
	 * This is ignored for other opt types.
	 */
	int switch_value;

	/**
	 * The name of the value, provided when creating usage information.
	 * This is required only for the functions that display usage
	 * information and only when a spec is of type `GITCLI_OPT_VALUE`.
	 */
	const char *value_name;

	/**
	 * Short description of the option, used when creating usage
	 * information.  This is only used when creating usage information.
	 */
	const char *help;

	/**
	 * Optional `gitcli_opt_usage_t`, used when creating usage information.
	 */
	gitcli_opt_usage_t usage;
} gitcli_opt_spec;

/** Return value for `gitcli_opt_parser_next`. */
typedef enum {
	/** Parsing is complete; there are no more arguments. */
	GITCLI_OPT_STATUS_DONE = 0,

	/**
	 * This argument was parsed correctly; the `opt` structure is
	 * populated and the value pointer has been set.
	 */
	GITCLI_OPT_STATUS_OK = 1,

	/**
	 * The argument could not be parsed correctly, it does not match
	 * any of the specifications provided.
	 */
	GITCLI_OPT_STATUS_UNKNOWN_OPTION = 2,

	/**
	 * The argument matched a spec of type `GITCLI_OPT_VALUE`, but no value
	 * was provided.
	 */
	GITCLI_OPT_STATUS_MISSING_VALUE = 3,
} gitcli_opt_status_t;

/** An option provided on the command-line. */
typedef struct gitcli_opt {
	/** The status of parsing the most recent argument. */
	gitcli_opt_status_t status;

	/**
	 * The specification that was provided on the command-line, or
	 * `NULL` if the argument did not match an `gitcli_opt_spec`.
	 */
	const gitcli_opt_spec *spec;

	/**
	 * The argument as it was specified on the command-line, including
	 * dashes, eg, `-f` or `--foo`.
	 */
	char *arg;

	/**
	 * If the spec is of type `GITCLI_OPT_VALUE` or `GITCLI_OPT_VALUE_OPTIONAL`,
	 * this is the value provided to the argument.
	 */
	char *value;
} gitcli_opt;

/* The internal parser state.  Callers should not modify this structure. */
typedef struct gitcli_opt_parser {
	const gitcli_opt_spec *specs;
	char **args;
	size_t args_len;

	size_t idx;
	size_t arg_idx;
	int in_literal : 1,
	in_short : 1;
} gitcli_opt_parser;

/**
 * Initializes a parser that parses the given arguments according to the
 * given specifications.
 *
 * @param parser The `gitcli_opt_parser` that will be initialized
 * @param specs A NULL-terminated array of `gitcli_opt_spec`s that can be parsed
 * @param argv The arguments that will be parsed
 * @param args_len The length of arguments to be parsed
 */
void gitcli_opt_parser_init(
	gitcli_opt_parser *parser,
	const gitcli_opt_spec specs[],
	char **argv,
	size_t args_len);

/**
 * Parses the next command-line argument and places the information about
 * the argument into the given `opt` data.
 *
 * @param opt The `gitcli_opt` information parsed from the argument
 * @param parser An `gitcli_opt_parser` that has been initialized with
 *        `gitcli_opt_parser_init`
 * @return true if the caller should continue iterating, or 0 if there are
 *         no arguments left to process.
 */
gitcli_opt_status_t gitcli_opt_parser_next(
	gitcli_opt *opt,
	gitcli_opt_parser *parser);

/**
 * Prints the status after parsing the most recent argument.  This is
 * useful for printing an error message when an unknown argument was
 * specified, or when an argument was specified without a value.
 *
 * @param file The file to print information to
 * @param opt The option that failed to parse
 * @return 0 on success, -1 on failure
 */
int gitcli_opt_status_fprint(
	FILE *file,
	const gitcli_opt *opt);

#endif /* CLI_opt_h__ */
